from typing import Protocol
import polars as pl


class Strategy(Protocol):
    def __init__(self, data: dict[str, pl.LazyFrame]):
        pass

    def generate_signals(self) -> pl.LazyFrame:
        """
        Generates signals for the strategy

        The resulting DataFrame should have the following columns:
        - strategy_name: The name of the strategy
        - symbol: The symbol for which the signal is generated
        - timestamp: The timestamp for which the signal is generated
        - open: The open price for the symbol at the timestamp
        - high: The high price for the symbol at the timestamp
        - low: The low price for the symbol at the timestamp
        - close: The close price for the symbol at the timestamp
        - volume: The volume for the symbol at the timestamp
        - signal: The signal generated for the symbol at the timestamp
        """
        pass


def signal_handler(signals_lf: list[pl.LazyFrame]) -> pl.LazyFrame:
    """
    Handles the signals generated by the strategies
    """
    results = None
    for signal in signals_lf:
        if results is None:
            results = signal
        else:
            results = results.vstack(signal)
    return results.lazy().sort("timestamp")
